services:
  llm-server:
    build:
      context: .
      dockerfile: Dockerfile.llm-server
    container_name: llm-server
    volumes:
      - ./models:/app/models
      - ./settings.ini:/app/settings.ini
      - ./requirements.txt:/app/requirements.txt
      - ./local_llm_server.py:/app/local_llm_server.py
      - ./run_server.py:/app/run_server.py
    environment:
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - "8000:8000"
    restart: unless-stopped
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram-bot
    volumes:
      - ./settings.ini:/app/settings.ini
      - ./.env:/app/.env
      - ./bot.py:/app/bot.py
      - ./run_bot.py:/app/run_bot.py
      - ./stub_loader.py:/app/stub_loader.py
      - ./openai_stub.py:/app/openai_stub.py
      - ./anthropic_stub.py:/app/anthropic_stub.py
      - ./language_tool_stub.py:/app/language_tool_stub.py
      - ./requirements_bot.txt:/app/requirements_bot.txt
    environment:
      - PYTHONUNBUFFERED=1
      - USE_STUBS=true
    depends_on:
      - llm-server
    restart: unless-stopped

volumes:
  models:
    driver: local 